// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	gocui "github.com/jroimartin/gocui"
	display "github.com/thejasbabu/track-it/pkg/task/display"

	mock "github.com/stretchr/testify/mock"
)

// Popup is an autogenerated mock type for the Popup type
type Popup struct {
	mock.Mock
}

// Close provides a mock function with given fields: gui
func (_m *Popup) Close(gui *gocui.Gui) error {
	ret := _m.Called(gui)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gocui.Gui) error); ok {
		r0 = rf(gui)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Show provides a mock function with given fields: gui, pos, data
func (_m *Popup) Show(gui *gocui.Gui, pos display.Position, data interface{}) error {
	ret := _m.Called(gui, pos, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gocui.Gui, display.Position, interface{}) error); ok {
		r0 = rf(gui, pos, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
