// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Badger is an autogenerated mock type for the Badger type
type Badger struct {
	mock.Mock
}

// Delete provides a mock function with given fields: key
func (_m *Badger) Delete(key []byte) error {
	ret := _m.Called(key)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Read provides a mock function with given fields: accessFn
func (_m *Badger) Read(accessFn func([]byte) error) error {
	ret := _m.Called(accessFn)

	var r0 error
	if rf, ok := ret.Get(0).(func(func([]byte) error) error); ok {
		r0 = rf(accessFn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: key, value
func (_m *Badger) Update(key []byte, value []byte) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
